### ISSUE TITLE
About the video demo

### ISSUE THREAD

**Issue by yeyingdege** [intelligent-control-lab/Intent_Traj_Prediction#2]
Hi, I really appreciate the release of your work. In the video, I find that the filtered action is quit different from the original action and the filtered action seems not the action with the highest probability score. Can you explain how do you filter the actions?

**Comment by Walleclipse** [comment]
Hi,
In the filtering process, we run motion detection and filtering out the stationary part of the trajectory. (TrajectorySmoothing/MotinSampler part in [Kinect_Smoothing](https://github.com/intelligent-control-lab/Kinect_Smoothing) as reference.) 
If there are not any significant movements, we label the part as stationary.  Otherwise, we pick the action with the highest probability score. 
(ps: I think in the demo video, they may have time-delay between filtered action and action probabilities.)
